apiVersion: v1
kind: Secret
metadata:
  name: gestion-projet-secrets
  namespace: gestion-projet
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "admin123"
  KEYCLOAK_CREDENTIALS_SECRET: "backend-secret"
  POSTGRES_PASSWORD: "admin123"
  KEYCLOAK_DB_PASSWORD: "keycloak123"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"
